Fase 2/Evidencias Proyecto/Evidencias de sistema/Aplicación/Magikstock version 4/app/urls.py
from django.urls import path
from django.views.generic import RedirectView
from .views import home, T1_Stock, T2_Employees, T3_Dashboard, T4_Settings, CustomLoginView, T2_Employees_List, T2_Employees_Edit, T2_Employees_Delete, T1_Producto, T1_Categoria, T1_Proveedor, T1_edit_proveedor, eliminar_proveedor, T1_Edit_Categoria, eliminar_categoria, T1_Edit_Producto, eliminar_producto, update_product_quantity

urlpatterns = [
    path('', RedirectView.as_view(url='/accounts/login/', permanent=False)),
    path('accounts/login/', CustomLoginView.as_view(), name='login'),  # Usar la vista personalizada
    path('home/', home, name="home"),
    path('T1_Stock/', T1_Stock, name="T1_Stock"),
    path('T1_Producto/', T1_Producto, name='T1_Producto'),
    path('T1_Edit_Producto/editar/<int:producto_id>/', T1_Edit_Producto, name='editar_producto'),
    path('T1_Edit_Producto/eliminar/<int:producto_id>/', eliminar_producto, name='eliminar_producto'),
    path('update-product-quantity/', update_product_quantity, name='update_product_quantity'), 
    # Rutas categorias
    path('T1_Edit_Categoria/editar/<int:categoria_id>/', T1_Edit_Categoria, name='editar_categoria'),
    path('T1_Edit_Categoria/eliminar/<int:categoria_id>/', eliminar_categoria, name='eliminar_categoria'),
    path('T1_Categoria/', T1_Categoria, name='T1_Categoria'),
    # Rutas proveedor
    path('T1_Proveedor/', T1_Proveedor, name='T1_Proveedor'),
     path('T1_edit_proveedor/editar/<int:proveedor_id>/', T1_edit_proveedor, name='editar_proveedor'),
    path('T1_edit_proveedor/eliminar/<int:proveedor_id>/', eliminar_proveedor, name='eliminar_proveedor'),
    # Rutas empleados
    path('T2_Employees_List/', T2_Employees_List, name="T2_Employees_List"),  
    path('T2_Employees/', T2_Employees, name="T2_Employees"),
    path('T2_Employees/editar/<int:id>/', T2_Employees_Edit, name='T2_Employees_Edit'),
    path('T2_Employees/eliminar/<int:id>/', T2_Employees_Delete, name='T2_Employees_Delete'), 
    path('T3_Dashboard/', T3_Dashboard, name="T3_Dashboard"), 
    path('T4_Settings/', T4_Settings, name="T4_Settings"),
]

Fase 2/Evidencias Proyecto/Evidencias de sistema/Aplicación/Magikstock version 4/app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone


class Sucursal(models.Model):
    NOMBRES_SUCURSALES = [
        ('cafeteria', 'Cafetería'),
        ('heladeria', 'Heladería'),
    ]

    nombre = models.CharField(max_length=20, choices=NOMBRES_SUCURSALES, unique=True)
    direccion = models.CharField(max_length=255)

    def __str__(self):
        return self.get_nombre_display()


class Profile(models.Model):
    USER_TYPES = [
        ('empleado', 'Empleado'),
        ('administrador', 'Administrador'),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rut = models.CharField(max_length=20)
    num = models.CharField(max_length=20)
    rol = models.CharField(max_length=20, choices=USER_TYPES, default='empleado')
    sucursal = models.ForeignKey(Sucursal, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"{self.user.username} - {self.sucursal.nombre if self.sucursal else 'Sin Sucursal'}"

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    if hasattr(instance, 'profile'):
        instance.profile.save()
        
class Proveedor(models.Model):
    nombre_proveedor = models.CharField(max_length=128)
    telefono = models.CharField(max_length=20)  
    correo_proveedor = models.EmailField(max_length=250)
    
    def save(self, *args, **kwargs):
        # Normalizar el nombre antes de guardar: por ejemplo, convertir a minúsculas
        self.nombre_proveedor = self.nombre_proveedor.strip().lower()
        super(Proveedor, self).save(*args, **kwargs)

    def __str__(self):
        return self.nombre_proveedor 

class Categoria(models.Model):
    nombre_categoria = models.CharField(max_length=128)
    descripcion = models.CharField(max_length=500, blank=True)  # La descripción puede ser opcional
    
    def __str__(self):
        if self.descripcion:
            return f"{self.nombre_categoria} - {self.descripcion}"
        return self.nombre_categoria
    
class Producto(models.Model):
    nombre_producto = models.CharField(max_length=128)
    cantidad = models.IntegerField()
    id_categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    fecha_entrada = models.DateField(auto_now_add=True)
    id_proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre_producto
    
class MovimientoEmpleado(models.Model):
    TIPO_MOVIMIENTO_CHOICES = [
        ('agregar', 'Agregar'),
        ('restar', 'Restar'),
    ]

    empleado = models.ForeignKey('Profile', on_delete=models.CASCADE)
    producto = models.ForeignKey('Producto', on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    tipo_movimiento = models.CharField(max_length=10, choices=TIPO_MOVIMIENTO_CHOICES)
    fecha = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.empleado.user.username} {self.tipo_movimiento} {self.cantidad} de {self.producto.nombre_producto} el {self.fecha}"
    
    class Meta:
        permissions = [
            ("view_movimiento_empleado_history", "Puede ver el historial de movimientos de empleados")
        ]

Fase 2/Evidencias Proyecto/Evidencias de sistema/Aplicación/Magikstock version 4/app/templates/app/T1_Categoria.html
{% extends 'app/base.html' %}

{% block contenido %}
<h3 style="text-align: center;">Agregar Categoría</h3>
<br>
<div class="top-section">
    <section class="estilos_stock" id="agregar-categoria">
        {% if messages %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endfor %}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endif %}
        
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            
            <div class="button-container">
                <button type="submit" class="button-magikstock-mini">Agregar Categoría</button>
            </div>
        </form>
    </section>
</div>

<br>

<h3 style="text-align: center;">Lista de Categorías</h3>
<div class="table-responsive">
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Descripción</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for categoria in categorias %}
            <tr>
                <td data-label="Nombre:">{{ categoria.nombre_categoria }}</td>
                <td data-label="Descripción:">{{ categoria.descripcion }}</td>
                <td data-label="Acciones:">
                    <!-- Botón de Editar -->
                    <form action="{% url 'editar_categoria' categoria.id %}" method="get" style="display:inline;">
                        <button type="submit" class="btn btn-warning btn-sm">Editar</button>
                    </form>
                    
                    <!-- Botón de Eliminar -->
                    <form action="{% url 'eliminar_categoria' categoria.id %}" method="POST" style="display:inline;">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('¿Estás seguro de que quieres eliminar esta categoría?');">Eliminar</button>
                    </form>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="3">No hay categorías registradas</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>    
</div>
{% endblock %}

Fase 2/Evidencias Proyecto/Evidencias de sistema/Aplicación/Magikstock version 4/app/templates/app/T1_Edit_Categoria.html
{% extends 'app/base.html' %}

{% block contenido %}
<h3 style="text-align: center;">Editar Categoría</h3>
<br>
<div class="top-section">
    <section class="estilos_stock" id="editar-categoria">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            
            <div class="mt-3">
                <button type="submit" class="button-magikstock-mini">Actualizar</button>
                <button type="button" class="button-magikstock-mini" onclick="window.location.href='{% url 'T1_Categoria' %}'">Volver</button>
            </div>
        </form>
    </section>
</div>

{% endblock %}

Fase 2/Evidencias Proyecto/Evidencias de sistema/Aplicación/Magikstock version 4/app/templates/app/T1_Edit_Producto.html
{% extends 'app/base.html' %}

{% block contenido %}
<h3 style="text-align: center;">Editar Producto: {{ producto.nombre_producto }}</h3>
<br>
<div class="top-section">
    <section class="estilos_stock" id="editar-producto">
        {% if messages %}
            <div class="alert alert-dismissible fade show" role="alert">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endfor %}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endif %}
        
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            
            <div class="mt-3">
                <button type="submit" class="button-magikstock-mini">Actualizar</button>
                <button type="button" class="button-magikstock-mini" onclick="window.location.href='{% url 'T1_Producto' %}'">Volver</button>
            </div>
        </form>
    </section>
</div>

{% endblock %}

Fase 2/Evidencias Proyecto/Evidencias de sistema/Aplicación/Magikstock version 4/app/templates/app/T1_Producto.html
{% extends 'app/base.html' %}

{% block contenido %}

{% load static %}

<h3 style="text-align: center;">Registrar Producto</h3>
<br>
<div class="top-section">
    <section class="estilos_stock" id="registrar-producto">
        {% if messages %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endfor %}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endif %}
        
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            
            <div class="button-container">
                <button type="submit" class="button-magikstock-mini">Registrar Producto</button>
            </div>
        </form>
    </section>
</div>

<br>

<h3 style="text-align: center;">Lista de Productos</h3>
<div class="table-responsive">
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Cantidad</th>
                <th>Categoría</th>
                <th>Proveedor</th>
                <th>Fecha de Entrada</th>
                <th>
                    <div class="acciones-title">Acciones</div> <!-- Título del card -->
                </th>
            </tr>
        </thead>
        <tbody>
            {% for producto in productos %}
            <tr>
                <td data-label="Producto:">{{ producto.nombre_producto }}</td>
                <td data-label="Cantidad">
                    <button class="boton_x btn-danger update-quantity" data-action="subtract" data-id="{{ producto.id }}">-</button>
                    <span class="cantidad" id="cantidad-{{ producto.id }}">{{ producto.cantidad }}</span>
                    <button class="boton_x btn-success update-quantity" data-action="add" data-id="{{ producto.id }}">+</button>
                </td>
                <td data-label="Categoria">{{ producto.id_categoria.nombre_categoria }} - {{ producto.id_categoria.descripcion }}</td>
                <td data-label="Proveedor">{{ producto.id_proveedor.nombre_proveedor }}</td>
                <td>{{ producto.fecha_entrada }}</td>
                <td>
                    <button class="btn-action btn-warning btn-custom" onclick="window.location.href='{% url 'editar_producto' producto.id %}'">Editar</button>
                    <form class="form-eliminar" action="{% url 'eliminar_producto' producto.id %}" method="POST" style="display:inline;">
                        {% csrf_token %}
                        <button type="submit" class="btn-action btn-danger btn-custom" onclick="return confirm('¿Estás seguro de que quieres eliminar este producto?');">Eliminar</button>
                    </form>
                    <button class="boton_y btn-danger btn-custom update-quantity" data-action="subtract" data-id="{{ producto.id }}">-</button>
                    <button class="boton_y btn-success btn-custom update-quantity" data-action="add" data-id="{{ producto.id }}">+</button>
                </td>                
            </tr>
            {% empty %}
            <tr>
                <td colspan="6">No hay productos registrados</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'app/js/cantidad.js' %}"></script>



{% endblock %}




Fase 2/Evidencias Proyecto/Evidencias de sistema/Aplicación/Magikstock version 4/app/templates/app/T1_Proveedor.html
{% extends 'app/base.html' %}

{% block contenido %}

<h3 style="text-align: center;"> Agregar Proveedor</h3>
<Br>
<div class="top-section">
    <section class="estilos_stock" id="agregar-proveedor">
        

        {% if messages %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endfor %}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endif %}
        
        <form id="stockForm_proveedor" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            
            <div class="button-container">
                <button type="submit" class="button-magikstock-mini">Agregar</button>
            </div>
        </form>
    </section>
</div>
<br>
<!-- Nueva sección para mostrar la tabla con proveedores -->
<h3 style="text-align: center;"> Lista de Proveedores </h3>
<div class="table-responsive">
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Teléfono</th>
                <th>Correo Electrónico</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for proveedor in proveedores %}
            <tr>
                <td data-label="Nombre:">{{ proveedor.nombre_proveedor }}</td>
                <td data-label="Teléfono:">{{ proveedor.telefono }}</td>
                <td data-label="Mail:">{{ proveedor.correo_proveedor }}</td>
                <td data-label="Acciones:">
                    <!-- Botón de Editar -->
                    <form action="{% url 'editar_proveedor' proveedor.id %}" method="get" style="display:inline;">
                        <button type="submit" class="btn btn-warning btn-sm">Editar</button>
                    </form>
                    
                    <!-- Botón de Eliminar -->
                    <form action="{% url 'eliminar_proveedor' proveedor.id %}" method="POST" style="display:inline;">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('¿Estás seguro de que quieres eliminar este proveedor?');">Eliminar</button>
                    </form>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="4">No hay proveedores registrados</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>    
</div>


{% endblock %}

Fase 2/Evidencias Proyecto/Evidencias de sistema/Aplicación/Magikstock version 4/app/templates/app/T1_Stock.html
{% extends 'app/base.html' %}

{% block contenido %}

<h3 style="text-align: center;"> Bienvenido {{ user.username }} </h3>

{% endblock %}

Fase 2/Evidencias Proyecto/Evidencias de sistema/Aplicación/Magikstock version 4/app/templates/app/T1_edit_proveedor.html
{% extends 'app/base.html' %}

{% block contenido %}

<h3 style="text-align: center;"> Editar Proveedor</h3>
<br>
<div class="top-section">
    <section class="estilos_stock" id="editar-proveedor">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            
            <div class="mt-3">
                <button type="submit" class="button-magikstock-mini">Actualizar</button>
                <button type="button" class="button-magikstock-mini" onclick="window.location.href='{% url 'T1_Proveedor' %}'">Volver</button>
            </div>
        </form>
    </section>
</div>

{% endblock %}

Fase 2/Evidencias Proyecto/Evidencias de sistema/Aplicación/Magikstock version 4/app/templates/app/T2_Employees.html
{% extends 'app/base.html' %}

{% block contenido %}

{% load static %}

<h3> Registro de empleados </h3>

{% if messages %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endif %}

<form method="post" id="register-form" autocomplete="off">
    {% csrf_token %}
    <div class="container">
        <div class="row">
            <div class="col-md-6 form-group">
                <label for="username">Usuario</label>
                <input type="text" id="new-username" name="new-username" class="form-control" required autocomplete="off">
            </div>

            <div class="col-md-6 form-group">
                <label for="password">Contraseña</label>
                <input type="password" id="new-password" name="new-password" class="form-control" required autocomplete="off">
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 form-group">
                <label for="first_name">Nombre</label>
                <input type="text" id="first_name" name="first_name" class="form-control" required>
            </div>

            <div class="col-md-6 form-group">
                <label for="last_name">Apellido</label>
                <input type="text" id="last_name" name="last_name" class="form-control" required>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 form-group">
                <label for="email">Correo Electrónico</label>
                <input type="email" id="email" name="email" class="form-control" required>
            </div>

            <div class="col-md-6 form-group">
                <label for="rut">RUT</label>
                <input type="text" id="rut" name="rut" class="form-control" required>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 form-group">
                <label for="num">Número de Teléfono</label>
                <input type="text" id="num" name="num" class="form-control" required>
            </div>

            <div class="col-md-6 form-group">
                <label for="rol">Rol</label>
                <select id="rol" name="rol" class="form-control" required>
                    <option value="">Seleccione el rol</option>
                    <option value="empleado">Empleado</option>
                    <option value="administrador">Administrador</option>
                </select>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 form-group">
                <label for="sucursal">Sucursal</label>
                <select id="sucursal" name="sucursal" class="form-control" required>
                    <option value="">Seleccione una sucursal</option>
                    {% for sucursal in sucursales %}
                        <option value="{{ sucursal.id }}">{{ sucursal.get_nombre_display }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>

        <div class="mt-3">
            <!-- Botón para guardar cambios -->
            <button type="submit" class="button-settings">Registrar Usuario</button>
            
            <!-- Botón para volver a la lista de empleados sin guardar -->
            <button type="button" class="button-settings" onclick="window.location.href='{% url 'T2_Employees_List' %}'">Volver</button>
        </div>
    </div>
</form>

<script src="{% static 'app/js/register.js' %}"></script>

{% endblock %}

Fase 2/Evidencias Proyecto/Evidencias de sistema/Aplicación/Magikstock version 4/app/templates/app/T2_Employees_Edit.html
{% extends 'app/base.html' %}

{% block contenido %}

{% load static %}

<h3>Editar Empleado</h3>


<form method="post" id="edit-form">
    {% csrf_token %}
    
    <div class="container" >
        <div class="row">
            <div class="col-md-6 form-group">
                <label for="first_name">Nombre</label>
                <input type="text" id="first_name" name="first_name" value="{{ empleado.user.first_name }}" class="form-control" required>
            </div>

            <div class="col-md-6 form-group">
                <label for="last_name">Apellido</label>
                <input type="text" id="last_name" name="last_name" value="{{ empleado.user.last_name }}" class="form-control" required>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 form-group">
                <label for="email">Correo Electrónico</label>
                <input type="email" id="email" name="email" value="{{ empleado.user.email }}" class="form-control" required>
            </div>

            <div class="col-md-6 form-group">
                <label for="rut">RUT</label>
                <input type="text" id="rut" name="rut" value="{{ empleado.rut }}" class="form-control" required>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 form-group">
                <label for="num">Número de Teléfono</label>
                <input type="text" id="num" name="num" value="{{ empleado.num }}" class="form-control" required>
            </div>

            <div class="col-md-6 form-group">
                <label for="rol">Rol</label>
                <select id="rol" name="rol" class="form-control">
                    <option value="empleado" {% if empleado.rol == "empleado" %}selected{% endif %}>Empleado</option>
                    <option value="administrador" {% if empleado.rol == "administrador" %}selected{% endif %}>Administrador</option>
                </select>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 form-group">
                <label for="sucursal">Sucursal</label>
                <select id="sucursal" name="sucursal" class="form-control" required>
                    <option value="">Seleccione una sucursal</option>
                    {% for sucursal in sucursales %}
                        <option value="{{ sucursal.id }}" {% if empleado.sucursal and empleado.sucursal.id == sucursal.id %}selected{% endif %}>{{ sucursal.get_nombre_display }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>

        <!-- Botones de Guardar y Volver -->
        <div class="mt-3">
            <!-- Botón para guardar cambios -->
            <button type="submit" class="button-settings">Guardar Cambios</button>
            
            <!-- Botón para volver a la lista de empleados sin guardar -->
            <button type="button" class="button-settings" onclick="window.location.href='{% url 'T2_Employees_List' %}'">Volver</button>
        </div>
    </div>
</form>

<script src="{% static 'app/js/register.js' %}"></script>

{% endblock %}

Fase 2/Evidencias Proyecto/Evidencias de sistema/Aplicación/Magikstock version 4/app/templates/app/T2_Employees_List.html
{% extends 'app/base.html' %}

{% block contenido %}

{% load static %}

<h3>Gestión de Empleados</h3>
<Br>
{% if messages %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endif %}
<Br>
<!-- Tabla para mostrar empleados registrados -->
<table class="table table-striped" id="tablaempleados">
    <thead>
        <tr>
            <th>Usuario</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Correo</th>
            <th>RUT</th>
            <th>Número</th>
            <th>Rol</th>
            <th>Sucursal</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for empleado in empleados %}
        <tr>
            <td data-label="Usuario">{{ empleado.user.username }}</td>
            <td data-label="Nombre">{{ empleado.user.first_name }}</td>
            <td data-label="Apellido">{{ empleado.user.last_name }}</td>
            <td data-label="Correo">{{ empleado.user.email }}</td>
            <td data-label="RUT">{{ empleado.rut }}</td>
            <td data-label="Número">{{ empleado.num }}</td>
            <td data-label="Rol">{{ empleado.get_rol_display }}</td>
            <td data-label="Sucursal">{{ empleado.sucursal.get_nombre_display}}</td>
            <td data-label="Acciones">
                <!-- Botón de Editar -->
                <form action="{% url 'T2_Employees_Edit' empleado.id %}" method="get" style="display:inline;">
                    <button type="submit" class="btn btn-warning btn-sm">Editar</button>
                </form>
                <!-- Botón de Eliminar -->
                <form action="{% url 'T2_Employees_Delete' empleado.id %}" method="post" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('¿Estás seguro de eliminar este usuario?');">Eliminar</button>
                </form>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="8" class="text-center">No hay empleados registrados.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<form method="get" action="{% url 'T2_Employees' %}">
    <button type="submit" class="button-magikstock-mini" >Registrar Usuario</button>
</form>

{% endblock %}


Fase 2/Evidencias Proyecto/Evidencias de sistema/Aplicación/Magikstock version 4/app/templates/app/T3_Dashboard.html
{% extends 'app/base.html' %}

{% block contenido %}
<h3 style="text-align: center;">Análisis de stock</h3>

<div style="width: 75%; margin: auto;">
    <canvas id="myChart"></canvas>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

<script>
    var ctx = document.getElementById('myChart').getContext('2d');

    // Datos pasados desde Django a través de JSON
    var proveedoresNombres = JSON.parse('{{ proveedores_nombres|escapejs }}');
    var proveedoresTelefonos = JSON.parse('{{ proveedores_telefonos|escapejs }}');

    // Crear el gráfico con los datos de proveedores
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: proveedoresNombres,  // Nombres de los proveedores
            datasets: [{
                label: 'Teléfonos de Proveedores',
                data: proveedoresTelefonos,  // Teléfonos de los proveedores
                backgroundColor: 'rgba(75, 192, 192, 0.2)',
                borderColor: 'rgba(75, 192, 192, 1)',
                borderWidth: 1
            }]
        },
        options: {
            scales: {
                y: {
                    beginAtZero: true
                }
            }
        }
    });
</script>

{% endblock %}

Fase 2/Evidencias Proyecto/Evidencias de sistema/Aplicación/Magikstock version 4/app/templates/app/home_empleado.html
{% extends 'app/base.html' %}

{% block contenido %}
<h2>Productos con Bajo Stock</h2>
<table>
    <thead>
        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
        </tr>
    </thead>
    <tbody>
        {% for producto in productos_bajo_stock %}
        <tr>
            <td>{{ producto.nombre_producto }}</td>
            <td>{{ producto.cantidad }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}